import random
import time
def mafia():
    print(" ")
    print(" M a f i a ")
    print(" ")
    playersN = input("How many players? ('type 4-10')")
    if playersN == "4":
        roleList = ["Mafia", "Citizen", "Citizen", "Doctor"]
        while len(roleList) > 0:    
            name = input("Name? ")
            role = random.choice(roleList)
            msg = ("{}, you are {}".format(name, role))
            roleList.remove(role)
            print(" ")
            print(" ")
            print(msg)
            print(" ")
            ready = input("Ready? (type 'y')")
            if ready == "y": 
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
        else: print("Gathering villagers...")
    if playersN == "5":
        roleList = ["Mafia", "Mafia", "Citizen", "Citizen", "Doctor"]
        while len(roleList) > 0:    
            name = input("Name? ")
            role = random.choice(roleList)
            msg = ("{}, you are {}".format(name, role))
            roleList.remove(role)
            print(" ")
            print(" ")
            print(msg)
            print(" ")
            ready = input("Ready? (type 'y')")
            if ready == "y":
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
        else: print("Gathering villagers...")
    if playersN == "6":
        roleList = ["Mafia", "Mafia", "Mafia", "Citizen", "Doctor", "Cop"]
        while len(roleList) > 0:    
            name = input("Name? ")
            role = random.choice(roleList)
            msg = ("{}, you are {}".format(name, role))
            roleList.remove(role)
            print(" ")
            print(" ")
            print(msg)
            print(" ")
            ready = input("Ready? (type 'y')")
            if ready == "y":
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
        else: print("Gathering villagers...")
    if playersN == "7":
        roleList = ["Mafia", "Mafia", "Mafia", "Citizen", "Citizen", "Doctor", "Cop"]
        while len(roleList) > 0:    
            name = input("Name? ")
            role = random.choice(roleList)
            msg = ("{}, you are {}".format(name, role))
            roleList.remove(role)
            print(" ")
            print(" ")
            print(msg)
            print(" ")
            ready = input("Ready? (type 'y')")
            if ready == "y":
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
        else: print("Gathering villagers...")
    if playersN == "8":
        roleList = ["Mafia", "Mafia", "Mafia", "Citizen", "Citizen", "Citizen", "Doctor", "Cop"]
        while len(roleList) > 0:    
            name = input("Name? ")
            role = random.choice(roleList)
            msg = ("{}, you are {}".format(name, role))
            roleList.remove(role)
            print(" ")
            print(" ")
            print(msg)
            print(" ")
            ready = input("Ready? (type 'y')")
            if ready == "y":
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
        else: print("Gathering villagers...")
    if playersN == "9":
        roleList = ["Mafia", "Mafia", "Mafia", "Mafia", "Citizen", "Citizen", "Citizen", "Doctor", "Cop"]
        while len(roleList) > 0:    
            name = input("Name? ")
            role = random.choice(roleList)
            msg = ("{}, you are {}".format(name, role))
            roleList.remove(role)
            print(" ")
            print(" ")
            print(msg)
            print(" ")
            ready = input("Ready? (type 'y')")
            if ready == "y":
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
        else: print("Gathering villagers...")
    if playersN == "10":
        roleList = ["Mafia", "Mafia", "Mafia", "Mafia", "Citizen", "Citizen", "Citizen", "Citizen", "Doctor", "Cop"]
        while len(roleList) > 0:    
            name = input("Name? ")
            role = random.choice(roleList)
            msg = ("{}, you are {}".format(name, role))
            roleList.remove(role)
            print(" ")
            print(" ")
            print(msg)
            print(" ")
            ready = input("Ready? (type 'y')")
            if ready == "y":
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
                print(" > ")
                print(" v ")
                print(" < ")
                print(" ^ ")
        else: print("Gathering villagers...")

mafia()